/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  readTime?: number;
  featured?: boolean;
  publishedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Blog | SanityImageCrop | SanityImageHotspot | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/queries/blog-queries.ts
// Variable: BLOGS_QUERY
// Query: *[_type == "blog"]  | order(publishedAt desc)  [$start...$end]  {  _id,  title,  excerpt,  "slug": slug.current,  "heroImage": heroImage.asset->url,  readTime,  featured,  publishedAt}
export type BLOGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  excerpt: string | null;
  slug: string | null;
  heroImage: string | null;
  readTime: number | null;
  featured: boolean | null;
  publishedAt: string | null;
}>;
// Variable: FEATURED_BLOGS_QUERY
// Query: *[_type == "blog" && featured == true]  | order(publishedAt desc)  [0...3]  {  _id,  title,  excerpt,  "slug": slug.current,  "heroImage": heroImage.asset->url,  readTime,  featured,  publishedAt}
export type FEATURED_BLOGS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  excerpt: string | null;
  slug: string | null;
  heroImage: string | null;
  readTime: number | null;
  featured: true;
  publishedAt: string | null;
}>;
// Variable: BLOG_BY_SLUG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{    _id,    title,    excerpt,    "slug": slug.current,    "heroImage": heroImage.asset->url,    "heroImageAlt": heroImage.alt,    readTime,    publishedAt,    body  }
export type BLOG_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  excerpt: string | null;
  slug: string | null;
  heroImage: string | null;
  heroImageAlt: string | null;
  readTime: number | null;
  publishedAt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"blog\"]\n  | order(publishedAt desc)\n  [$start...$end]\n  \n{\n  _id,\n  title,\n  excerpt,\n  \"slug\": slug.current,\n  \"heroImage\": heroImage.asset->url,\n  readTime,\n  featured,\n  publishedAt\n}\n\n": BLOGS_QUERYResult;
    "\n  *[_type == \"blog\" && featured == true]\n  | order(publishedAt desc)\n  [0...3]\n  \n{\n  _id,\n  title,\n  excerpt,\n  \"slug\": slug.current,\n  \"heroImage\": heroImage.asset->url,\n  readTime,\n  featured,\n  publishedAt\n}\n\n": FEATURED_BLOGS_QUERYResult;
    "\n  *[_type == \"blog\" && slug.current == $slug][0]{\n    _id,\n    title,\n    excerpt,\n    \"slug\": slug.current,\n    \"heroImage\": heroImage.asset->url,\n    \"heroImageAlt\": heroImage.alt,\n    readTime,\n    publishedAt,\n    body\n  }\n": BLOG_BY_SLUG_QUERYResult;
  }
}
